let config_path = expand('~') . '/.config/nvim'
exec 'source' config_path . '/vimplug.vim'
exec 'source' config_path . '/sets.vim'
exec 'source' config_path . '/remaps.vim'
exec 'source' config_path . '/vimtex.vim'
